import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const themeScript = `
    (function(){
      try {
        var t = localStorage.getItem('theme');
        if (
          t === 'dark' ||
          (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)
        ) {
          document.documentElement.classList.add('dark');
        }
      } catch(e) {}
    })();
  `;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        
       
        <div
          dangerouslySetInnerHTML={{
            __html: `<script>${themeScript}</script>`,
          }}
        />

        {children}
      </body>
    </html>
  );
}